// ============================================================
// CONTROL PLANE — MFE INVOCATION
// ============================================================
// PLATFORM-CONTRACT v3.2 makes the daemon a render orchestrator: after the
// registry resolves {mfe, capability, props}, the daemon drives the resolved
// MFE's platform capabilities (authorizeAccess → load → render / refresh)
// and relays the RenderedExperience to renderers.
//
// The interfaces here keep DaemonService transport-agnostic (and unit
// testable); HttpMfeInvoker is the concrete implementation for MFEs that
// expose the standard capability endpoints generated by seans-mfe-tool:
//
//   POST /authorize · POST /load · POST /render · POST /refresh
// ============================================================

import type {
  MfeRegistration,
  RenderedExperience,
  Resolution,
  SessionContext,
} from '@seans-mfe/contracts';

/** Per-invocation context the daemon threads into every capability call. */
export interface MfeInvocationContext {
  /** Carried end-to-end from the originating action. */
  correlationId: string;
  /** Who/where this render is for — user, jwt, application, locale. */
  session?: SessionContext;
}

/** How the daemon looks up where a resolved MFE lives. */
export interface MfeDirectory {
  lookup(name: string): Promise<MfeRegistration | null>;
}

/** Drives the platform capabilities of a resolved MFE. */
export interface MfeInvoker {
  /** Gate check before render. Implementations should treat MFEs that do not
   *  declare `authorizeAccess` as open (return true). */
  authorizeAccess(mfe: MfeRegistration, context: MfeInvocationContext): Promise<boolean>;
  /** One-time initialization before the first render of an MFE. */
  load(mfe: MfeRegistration, context: MfeInvocationContext): Promise<void>;
  /** Render the resolved capability with the resolution props. */
  render(
    mfe: MfeRegistration,
    resolution: Resolution,
    context: MfeInvocationContext,
  ): Promise<RenderedExperience>;
  /** Data reload when the same MFE+capability stays selected. */
  refresh(
    mfe: MfeRegistration,
    resolution: Resolution,
    context: MfeInvocationContext,
  ): Promise<void>;
}

// ── Directory: static / programmatic registrations ───────────

/**
 * Directory backed by an in-memory map. Seeded from `DaemonServiceConfig.mfes`
 * and extended at runtime via `register()` (e.g. when the registry relays a
 * describe() registration).
 */
export class StaticMfeDirectory implements MfeDirectory {
  private readonly mfes = new Map<string, MfeRegistration>();

  constructor(registrations: MfeRegistration[] = []) {
    for (const registration of registrations) this.register(registration);
  }

  register(registration: MfeRegistration): void {
    this.mfes.set(registration.name, registration);
  }

  async lookup(name: string): Promise<MfeRegistration | null> {
    return this.mfes.get(name) ?? null;
  }
}

// ── Invoker: HTTP capability endpoints ───────────────────────

export interface HttpMfeInvokerOptions {
  /** Per-call deadline in milliseconds. Default: 4000 (forward timeout). */
  timeoutMs?: number;
  /** Injectable for tests; defaults to the global fetch (Node ≥18, browsers). */
  fetchImpl?: typeof fetch;
}

/**
 * Calls the standard capability endpoints of an SMT-generated MFE.
 * Bodies follow PLATFORM-CONTRACT.md § Capability Details; the session JWT
 * travels as the Authorization header on every call.
 */
export class HttpMfeInvoker implements MfeInvoker {
  private readonly timeoutMs: number;
  private readonly fetchImpl: typeof fetch;

  constructor(options: HttpMfeInvokerOptions = {}) {
    this.timeoutMs = options.timeoutMs ?? 4_000;
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  async authorizeAccess(mfe: MfeRegistration, context: MfeInvocationContext): Promise<boolean> {
    if (!mfe.capabilities.includes('authorizeAccess')) return true;
    const body = await this.post(mfe, '/authorize', context, {
      inputs: { token: context.session?.jwt ?? null, context: this.contextInputs(context) },
    });
    return body.authorized === true;
  }

  async load(mfe: MfeRegistration, context: MfeInvocationContext): Promise<void> {
    await this.post(mfe, '/load', context, {
      inputs: { config: {} },
      context: this.contextInputs(context),
    });
  }

  async render(
    mfe: MfeRegistration,
    resolution: Resolution,
    context: MfeInvocationContext,
  ): Promise<RenderedExperience> {
    const body = await this.post(mfe, '/render', context, {
      inputs: { capability: resolution.capability, props: resolution.props },
      context: this.contextInputs(context),
    });
    // Contract response: { status: 'rendered', element: { contentType, output } }
    const element = (body.element ?? {}) as Record<string, unknown>;
    return {
      id: typeof body.id === 'string' ? body.id : globalThis.crypto.randomUUID(),
      mfe: mfe.name,
      capability: resolution.capability,
      output: 'output' in element ? element.output : body.element ?? body,
      contentType:
        typeof element.contentType === 'string'
          ? element.contentType
          : mfe.contentType ?? 'application/json',
      props: resolution.props,
      createdAt: new Date().toISOString(),
    };
  }

  async refresh(
    mfe: MfeRegistration,
    resolution: Resolution,
    context: MfeInvocationContext,
  ): Promise<void> {
    await this.post(mfe, '/refresh', context, {
      inputs: { full: false, capability: resolution.capability, props: resolution.props },
      context: this.contextInputs(context),
    });
  }

  /** The subset of SessionContext the MFE's shared Context understands. */
  private contextInputs(context: MfeInvocationContext): Record<string, unknown> {
    return {
      requestId: context.correlationId,
      sessionId: context.session?.sessionId ?? null,
      user: context.session?.user ?? null,
      application: context.session?.application ?? null,
      locale: context.session?.locale ?? null,
    };
  }

  private async post(
    mfe: MfeRegistration,
    path: string,
    context: MfeInvocationContext,
    body: Record<string, unknown>,
  ): Promise<Record<string, unknown>> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      const headers: Record<string, string> = { 'content-type': 'application/json' };
      if (context.session?.jwt) headers.authorization = `Bearer ${context.session.jwt}`;
      const response = await this.fetchImpl(`${mfe.baseUrl.replace(/\/$/, '')}${path}`, {
        method: 'POST',
        headers,
        body: JSON.stringify(body),
        signal: controller.signal,
      });
      if (!response.ok) {
        throw new Error(`MFE ${mfe.name}${path} responded ${response.status}`);
      }
      const parsed: unknown = await response.json();
      return typeof parsed === 'object' && parsed !== null
        ? (parsed as Record<string, unknown>)
        : {};
    } finally {
      clearTimeout(timer);
    }
  }
}
